import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './Navbar'
import Footer from './Footer'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Portifolio',
  description: 'Generated by create ASU tech',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      
      <body className="bg-white">
        <Navbar/>
        {children}
        <Footer/>
      </body>
      
    </html>
  )
}
